"use client";
import {useState,useTransition,type FormEvent} from "react";
import {useRouter} from "next/navigation";
import {saveReview,removeReview} from "@/app/app/review/actions";
import {reviewText,validatePurchaseReview} from "@/lib/review-validation";
import type {OwnReview} from "@/app/app/review/types";
const statuses:Record<string,string>={approved:"Disetujui dan tayang",pending:"Menunggu persetujuan admin",hidden:"Disembunyikan admin"};
export default function ReviewEditor({own,orderId,defaultName}:{own:OwnReview|null;orderId:string;defaultName:string}){
 const [rating,setRating]=useState(own?.rating??0),[comment,setComment]=useState(own?.comment??""),[displayName,setDisplayName]=useState(own?.displayName??defaultName),[message,setMessage]=useState(""),[confirm,setConfirm]=useState(false);
 const [pending,startTransition]=useTransition();const router=useRouter();
 function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const input={orderId,rating,comment,displayName};const invalid=validatePurchaseReview(input);if(invalid){setMessage(invalid);return;}startTransition(async()=>{try{const result=await saveReview(input);setMessage(result.error??(own?.status==="hidden"?"Perubahan tersimpan. Ulasan tetap disembunyikan sampai ditinjau admin.":"Ulasan tersimpan dan menunggu persetujuan admin."));if(!result.error){setComment(reviewText(comment));setDisplayName(reviewText(displayName));router.refresh();}}catch{setMessage("Ulasan belum tersimpan. Coba lagi sebentar, ya.");}});}
 function remove(){if(!own)return;startTransition(async()=>{try{const result=await removeReview(own.id);setMessage(result.error??"Ulasan terhapus.");if(!result.error)router.refresh();}catch{setMessage("Ulasan belum terhapus.");}});}
 return <section aria-busy={pending} className="mt-6 rounded-[36px] bg-white p-5 shadow-soft sm:p-8"><h2 className="text-xl font-medium">{own?"Edit ulasan pesananmu":"Bagikan pengalaman pembelianmu"}</h2>{own&&<div className="mt-3 rounded-2xl bg-lilac p-4 text-xs text-purple-800"><p>Status: {statuses[own.status]??own.status}</p>{own.note&&<p className="mt-2">Catatan admin: {own.note}</p>}</div>}<form onSubmit={save} className="mt-5"><fieldset disabled={pending} className="space-y-5"><div><label htmlFor="review-rating" className="block text-sm">Bintang (wajib)</label><select id="review-rating" required value={rating} onChange={e=>setRating(Number(e.target.value))} className="mt-2 rounded-full border border-[#EADFF2] px-5 py-3 text-sm"><option value={0} disabled>Pilih bintang</option>{[5,4,3,2,1].map(value=><option key={value} value={value}>{value} ★</option>)}</select></div><div><label htmlFor="review-name" className="text-sm">Nama tampilan</label><input id="review-name" required maxLength={60} value={displayName} onChange={e=>setDisplayName(e.target.value)} aria-describedby="review-name-help" className="mt-2 w-full rounded-full border border-[#EADFF2] px-5 py-3 text-sm focus:outline-purple-600"/><p id="review-name-help" className="mt-2 text-xs text-muted">Nama ini tampil publik. Kamu boleh menyamarkannya, misalnya Ak***a.</p></div><div><label htmlFor="review-comment" className="text-sm">Komentar (10–500 karakter)</label><textarea id="review-comment" required minLength={10} maxLength={500} rows={4} value={comment} onChange={e=>setComment(e.target.value)} placeholder="Apa yang membantu dan apa yang bisa kami perbaiki?" className="mt-2 w-full rounded-2xl border border-[#EADFF2] p-4 text-sm focus:outline-purple-600"/><p className="text-right text-xs text-muted">{comment.length}/500 karakter</p></div><button type="submit" className="btn btn-brand text-sm">{pending?"Memproses…":"Simpan ulasan →"}</button></fieldset></form>{own&&<div className="mt-4">{confirm?<div className="rounded-2xl bg-peach p-4"><p className="text-sm">Hapus ulasan ini? Tindakan ini tidak bisa dibatalkan.</p><div className="mt-3 flex gap-2"><button disabled={pending} onClick={remove} className="btn btn-ghost text-xs">Ya, hapus</button><button disabled={pending} onClick={()=>setConfirm(false)} className="btn btn-ghost text-xs">Batal</button></div></div>:<button disabled={pending} onClick={()=>setConfirm(true)} className="btn btn-ghost text-xs">Hapus ulasan ini</button>}</div>}<p role="status" className="mt-4 text-sm text-purple-800">{message}</p></section>;
}
