"use client";
import {useEffect,useId,useRef,useState,useTransition} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {voteReview,reportReview} from "@/app/app/review/actions";
import {loadPublishedReviews} from "@/app/review/actions";
import type {PublicReview,ReviewPageData} from "@/app/app/review/types";
function ReviewItem({review,authenticated}:{review:PublicReview;authenticated:boolean}){
  const [report,setReport]=useState(false),[reason,setReason]=useState("spam"),[message,setMessage]=useState("");const [pending,startTransition]=useTransition();const router=useRouter();
  function run(kind:"vote"|"report"){startTransition(async()=>{try{const result=kind==="vote"?await voteReview(review.id,!review.voted):await reportReview(review.id,reason);setMessage(result.error??(kind==="report"?"Laporan terkirim. Terima kasih sudah menjaga ruang ini.":"Vote diperbarui."));if(!result.error){setReport(false);router.refresh();}}catch{setMessage("Belum tersimpan. Coba lagi sebentar, ya.");}});}
  return <article className="feature-card rounded-[36px] bg-white p-5 shadow-soft sm:p-7"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-medium text-purple-800">{review.name}</p><span aria-label={`${review.rating} dari 5 bintang`} className="text-sm tracking-widest text-magenta-600">{"★".repeat(review.rating)}{"☆".repeat(5-review.rating)}</span></div><p className="mt-2 text-[10px] text-muted">{new Intl.DateTimeFormat("id-ID",{dateStyle:"long",timeZone:"UTC"}).format(new Date(`${review.day}T00:00:00Z`))}</p>{(review.planName||review.title)&&<h3 className="mt-4 break-words text-lg font-medium">{review.planName?`Pembelian ${review.planName}`:review.title}</h3>}<p className="mt-3 whitespace-pre-wrap break-words text-sm leading-relaxed text-muted">{review.body}</p><div className="mt-5 flex flex-wrap gap-2">{authenticated?<><button disabled={pending} aria-pressed={review.voted} onClick={()=>run("vote")} className={`btn text-xs disabled:opacity-60 ${review.voted?"btn-brand":"btn-ghost"}`}>Membantu · {review.helpful}</button><button disabled={pending} aria-expanded={report} onClick={()=>setReport(!report)} className="btn btn-ghost text-xs">Laporkan</button></>:<><Link href="/app/review" className="btn btn-ghost text-xs">Membantu · {review.helpful}</Link><Link href="/app/review" className="btn btn-ghost text-xs">Masuk untuk melaporkan</Link></>}</div>{report&&<div className="mt-4 rounded-2xl bg-peach p-4"><label className="text-xs">Alasan laporan<select value={reason} disabled={pending} onChange={event=>setReason(event.target.value)} className="ml-3 rounded-full border border-[#EADFF2] p-2 text-xs"><option value="spam">Spam</option><option value="sara">SARA</option><option value="lainnya">Lainnya</option></select></label><button disabled={pending} onClick={()=>run("report")} className="btn btn-ghost ml-2 mt-2 text-xs">Kirim laporan</button></div>}<p role="status" className="mt-3 text-xs text-purple-800">{message}</p></article>;
}
export default function ReviewBoard({initial,authenticated}:{initial:ReviewPageData;authenticated:boolean}){
 const [data,setData]=useState(initial),[message,setMessage]=useState(""),[busy,startTransition]=useTransition();const heading=useId();const generation=useRef(0);
 useEffect(()=>{generation.current++;setData(initial);setMessage("");},[initial]);
 function load(stars:number,sort:"newest"|"helpful",more=false){const current=++generation.current;setMessage("");startTransition(async()=>{try{const next=await loadPublishedReviews({stars,sort,page:more?data.page+1:0});if(current!==generation.current)return;if(next.error){setMessage("Ulasan belum bisa dimuat. Coba lagi sebentar, ya.");return;}setData(previous=>({...next,reviews:more?[...previous.reviews,...next.reviews.filter(row=>!previous.reviews.some(old=>old.id===row.id))]:next.reviews}));}catch{if(current===generation.current)setMessage("Periksa koneksi dan coba lagi, ya.");}});}
 const {reviews,summary,stars,sort}=data;
 if(data.error)return <section className="mt-8"><h2 className="text-xl font-medium">Ulasan Pelanggan</h2><p role="alert" className="mt-4 rounded-2xl bg-peach p-5 text-sm">Ulasan belum bisa dimuat. Coba muat ulang sebentar lagi, ya.</p></section>;
 return <section aria-labelledby={heading} aria-busy={busy} className="mt-10"><h2 id={heading} className="text-xl font-medium">Ulasan Pelanggan</h2><p className="mt-2 text-sm text-muted">Pengalaman dari pembelian yang disetujui, ditinjau admin sebelum ditampilkan.</p><div className="mt-5 grid gap-6 rounded-[36px] bg-lilac p-6 sm:grid-cols-[1fr_2fr]"><div><p className="text-5xl font-semibold text-purple-800">{summary.total?summary.average.toLocaleString("id-ID",{maximumFractionDigits:1}):"—"}<span className="text-lg font-normal text-muted"> / 5</span></p><p className="mt-3 text-xs text-muted">{summary.total} ulasan disetujui</p></div><div className="space-y-2">{summary.distribution.map(({rating,count})=><div key={rating} className="flex items-center gap-3 text-xs text-purple-800"><span className="w-7">{rating} ★</span><div aria-hidden="true" className="h-2 flex-1 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full" style={{width:`${summary.total?count/summary.total*100:0}%`,background:"var(--grad-brand)"}}/></div><span className="w-8 text-right">{count}</span></div>)}</div></div><div role="group" aria-label="Filter bintang" className="mt-6 flex flex-wrap gap-2">{[0,5,4,3,2,1].map(value=><button disabled={busy} key={value} aria-pressed={stars===value} onClick={()=>load(value,sort)} className={`btn text-xs disabled:opacity-60 ${stars===value?"btn-brand":"btn-ghost"}`}>{value===0?"Semua":`${value} ★`}</button>)}<label className="sr-only" htmlFor={`${heading}-sort`}>Urutkan ulasan</label><select disabled={busy} id={`${heading}-sort`} value={sort} onChange={e=>load(stars,e.target.value==="helpful"?"helpful":"newest")} className="rounded-full border border-[#EADFF2] bg-white px-4 py-2 text-xs"><option value="newest">Terbaru</option><option value="helpful">Paling membantu</option></select></div><p role="status" className="my-4 text-xs text-muted">{busy?"Memuat ulasan…":`${reviews.length} dari ${data.total} ulasan sesuai filter`}</p>{message&&<p role="alert" className="mb-4 rounded-2xl bg-peach p-4 text-sm">{message}</p>}{reviews.length?<div className="grid gap-5 lg:grid-cols-2">{reviews.map(review=><ReviewItem key={review.id} review={review} authenticated={authenticated}/>)}</div>:<p className="rounded-[24px] bg-white p-6 text-sm text-muted">Belum ada ulasan untuk pilihan ini. Pengalamanmu akan membantu teman lain memilih paket.</p>}{reviews.length<data.total&&<button disabled={busy} onClick={()=>load(stars,sort,true)} className="btn btn-ghost mt-6 text-sm disabled:opacity-60">{busy?"Memuat…":"Lihat lebih banyak →"}</button>}</section>;
}
