"use client";
import {useEffect,useState,type FormEvent} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {supabaseBrowser} from "@/lib/supabase";
import {saveName} from "@/app/app/pengaturan/actions";
import DashboardLogout from "./DashboardLogout";
import {rupiah} from "@/app/app/premium/types";
type Order={id:string;name:string;amount:number;status:string;date:string};
const tabs=[{id:"profil",label:"Profil"},{id:"akun",label:"Akun"},{id:"langganan",label:"Langganan"},{id:"privasi",label:"Privasi"}];
const statuses:Record<string,string>={pending:"Menunggu pembayaran",awaiting_verification:"Menunggu verifikasi",paid:"Disetujui",rejected:"Ditolak",expired:"Kedaluwarsa"};
const date=(value:string)=>new Intl.DateTimeFormat("id-ID",{dateStyle:"long",timeZone:"Asia/Jakarta"}).format(new Date(value));
function authError(message:string){if(/already|registered|exists/i.test(message))return "Email ini sudah digunakan.";if(/password|weak/i.test(message))return "Gunakan password baru yang kuat, minimal 8 karakter.";if(/rate|too many|seconds/i.test(message))return "Terlalu banyak percobaan. Tunggu sebentar, ya.";if(/reauth|session|token/i.test(message))return "Masuk kembali sebelum mengubah akun, ya.";return "Perubahan belum tersimpan. Periksa isian dan coba lagi.";}
export default function SettingsPanel({name,avatar,email,initialTab,until,plan,history,loadError}:{name:string;avatar:string|null;email:string;initialTab:string;until:string|null;plan:string;history:Order[];loadError:boolean}){
 const router=useRouter();const [tab,setTab]=useState(initialTab);const [nickname,setNickname]=useState(name);const [newEmail,setEmail]=useState(email);const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [show,setShow]=useState(false);const [deletion,setDeletion]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 useEffect(()=>{setTab(tabs.some(t=>t.id===initialTab)?initialTab:"profil");},[initialTab]);
 async function run(task:()=>Promise<void>){setBusy(true);setMessage("");try{await task();}catch{setMessage("Periksa koneksi dan coba lagi, ya.");}finally{setBusy(false);}}
 async function upload(file:File|undefined){if(!file)return;await run(async()=>{
 if(file.size===0||file.size>2*1024*1024||!["image/jpeg","image/png","image/webp"].includes(file.type)){setMessage("Pilih JPG, PNG, atau WebP maksimal 2 MB.");return;}
 const bitmap=await createImageBitmap(file);try{
 const canvas=document.createElement("canvas");canvas.width=512;canvas.height=512;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("canvas");
 const side=Math.min(bitmap.width,bitmap.height);ctx.fillStyle="#FDE6F1";ctx.fillRect(0,0,512,512);ctx.drawImage(bitmap,(bitmap.width-side)/2,(bitmap.height-side)/2,side,side,0,0,512,512);
 const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error("image")),"image/jpeg",.86));
 const form=new FormData();form.set("avatar",new File([blob],"avatar.jpg",{type:"image/jpeg"}));const response=await fetch("/app/pengaturan/avatar",{method:"POST",body:form});const result=await response.json();
 setMessage(response.ok?"Foto profil tersimpan.":result.error??"Foto belum tersimpan.");if(response.ok)router.refresh();
 }finally{bitmap.close();}
 });}
 const submitName=(event:FormEvent)=>{event.preventDefault();void run(async()=>{const result=await saveName(nickname);setMessage(result.error??"Nama panggilan tersimpan.");if(!result.error)router.refresh();});};
 const submitEmail=(event:FormEvent)=>{event.preventDefault();void run(async()=>{if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(newEmail.trim())){setMessage("Isi alamat email yang valid.");return;}const {error}=await supabaseBrowser().auth.updateUser({email:newEmail.trim()},{emailRedirectTo:`${window.location.origin}/auth/callback?next=/app/pengaturan?tab=akun`});setMessage(error?authError(error.message):"Cek email lama dan baru untuk konfirmasi perubahan email.");});};
 const submitPassword=(event:FormEvent)=>{event.preventDefault();void run(async()=>{if(password.length<8){setMessage("Password minimal 8 karakter.");return;}if(password!==confirm){setMessage("Konfirmasi password belum sama.");return;}const {error}=await supabaseBrowser().auth.updateUser({password});setMessage(error?authError(error.message):"Password berhasil diganti.");if(!error){setPassword("");setConfirm("");}});};
 async function exportData(){await run(async()=>{const response=await fetch("/app/pengaturan/export");if(!response.ok){const result=await response.json();setMessage(result.error);return;}const url=URL.createObjectURL(await response.blob());const link=document.createElement("a");link.href=url;link.download="ceritakita-data.json";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage("Data pribadimu telah diunduh.");});}
 async function deleteAccount(){if(deletion!=="HAPUS")return;await run(async()=>{const response=await fetch("/app/pengaturan/delete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({confirmation:deletion})});const result=await response.json();if(!response.ok){setMessage(result.error);return;}await supabaseBrowser().auth.signOut({scope:"local"});router.replace("/masuk");router.refresh();});}
 return <div className="settings-space"><div className="settings-tabs" role="tablist" aria-label="Pengaturan">{tabs.map(t=><button key={t.id} id={`tab-${t.id}`} type="button" role="tab" tabIndex={tab===t.id?0:-1} onKeyDown={event=>{const index=tabs.findIndex(item=>item.id===t.id);const next=event.key==="ArrowRight"?(index+1)%tabs.length:event.key==="ArrowLeft"?(index+tabs.length-1)%tabs.length:event.key==="Home"?0:event.key==="End"?tabs.length-1:-1;if(next<0)return;event.preventDefault();const target=tabs[next].id;setTab(target);setMessage("");document.getElementById(`tab-${target}`)?.focus();router.replace(`/app/pengaturan?tab=${target}`,{scroll:false});}} aria-selected={tab===t.id} aria-controls={`panel-${t.id}`} onClick={()=>{setTab(t.id);setMessage("");router.replace(`/app/pengaturan?tab=${t.id}`,{scroll:false});}}>{t.label}</button>)}</div>
 {loadError&&<p role="alert" className="my-4 text-sm">Sebagian data belum tersedia. Coba muat ulang halaman.</p>}
 <section id={`panel-${tab}`} role="tabpanel" aria-labelledby={`tab-${tab}`} className="settings-card">
 {tab==="profil"&&<><h2>Profil yang terasa seperti kamu</h2><p className="text-muted">Nama panggilan dan foto untuk ruang pribadimu.</p><div className="my-6 flex flex-wrap items-center gap-5">{avatar?<img src={avatar} alt="Foto profilmu" width={88} height={88} className="h-[88px] w-[88px] rounded-full object-cover"/>:<span className="flex h-[88px] w-[88px] items-center justify-center rounded-full bg-blush text-3xl text-purple-800">{name.slice(0,1)}</span>}<label>Ubah foto profil<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{void upload(e.target.files?.[0]);e.target.value="";}}/><small>Privat · maks. 2 MB · dipotong persegi 512 × 512.</small></label></div><form onSubmit={submitName}><label>Nama panggilan<input value={nickname} onChange={e=>setNickname(e.target.value)} required maxLength={60} autoComplete="nickname"/></label><button disabled={busy} className="btn btn-brand">Simpan profil →</button></form></>}
 {tab==="akun"&&<><h2>Akunmu</h2><form onSubmit={submitEmail}><label>Email<input type="email" value={newEmail} onChange={e=>setEmail(e.target.value)} required maxLength={254} autoComplete="email"/></label><button disabled={busy} className="btn btn-ghost">Ganti email →</button></form><form onSubmit={submitPassword} className="mt-8 border-t border-[#EADFF2] pt-6"><label>Password baru<input type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} required minLength={8} autoComplete="new-password"/></label><label>Konfirmasi password<input type={show?"text":"password"} value={confirm} onChange={e=>setConfirm(e.target.value)} required minLength={8} autoComplete="new-password"/></label><button type="button" className="mb-4 text-xs text-purple-800 underline" aria-pressed={show} onClick={()=>setShow(!show)}>{show?"Sembunyikan":"Tampilkan"} password</button><br/><button disabled={busy} className="btn btn-brand">Simpan password →</button></form><div className="mt-8"><DashboardLogout/></div></>}
 {tab==="langganan"&&<><h2>Paket {plan}</h2><p className="my-3 text-muted">{until?`Aktif hingga ${date(until)}${new Date(until).getTime()<=Date.now()?" · sudah berakhir":""}`:"Kamu menggunakan fitur Gratis."}</p><Link href="/app/premium" className="btn btn-brand">Lihat pilihan paket →</Link><h3 className="mb-4 mt-8 text-lg">Riwayat order</h3>{history.length?history.map(o=><article key={o.id} className="settings-order"><div><strong>{o.name}</strong><p className="text-xs text-muted">{date(o.date)} · {statuses[o.status]??"Status belum tersedia"}</p></div><div className="flex flex-wrap items-center gap-3"><span>{rupiah(o.amount)}</span>{o.status==="paid"&&o.amount>0&&<Link href={`/app/review?order=${o.id}`} className="btn btn-ghost text-xs">Beri Ulasan / Edit Ulasan</Link>}</div></article>):<p className="text-sm text-muted">Belum ada pesanan. Pilih paket saat kamu siap.</p>}</>}
 {tab==="privasi"&&<><h2>Kendali ada di tanganmu</h2><p className="my-3 text-sm text-muted">Unduh mood, jurnal, dan cerita milikmu dalam berkas JSON.</p><button disabled={busy} onClick={()=>void exportData()} className="btn btn-ghost">Ekspor data saya ↓</button><div className="mt-8 rounded-[24px] bg-peach p-5"><h3 className="text-lg">Hapus akun</h3><p className="my-3 text-sm leading-relaxed">Akun, foto, bukti pembayaran, dan seluruh data milikmu akan dihapus permanen. Unduh datamu terlebih dahulu jika ingin menyimpannya.</p><label>Ketik HAPUS untuk konfirmasi<input value={deletion} onChange={e=>setDeletion(e.target.value)} autoComplete="off" placeholder="HAPUS" maxLength={5}/></label><button disabled={busy||deletion!=="HAPUS"} onClick={()=>void deleteAccount()} className="btn btn-ghost !border-red-300 !text-red-700">Hapus akun saya</button></div></>}
 </section><p role="status" aria-live="polite" className="my-4 text-sm text-purple-800">{busy?"Sedang memproses…":message}</p></div>;
}
