"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import type {ModerationReview} from "@/lib/moderation-types";
import {reviewModerationLabels as moderationLabels} from "@/lib/moderation-types";
import {moderateReview} from "@/app/admin/(panel)/review/actions";
import DataTable from "./DataTable";
import Modal from "./Modal";
import StatusBadge from "./StatusBadge";
import Toast from "./Toast";
const input="w-full rounded-2xl border border-[#EADFF2] bg-white p-3 text-sm focus:outline-purple-600";
type Action="hidden"|"removed"|"restore"|"feature"|"note";
export default function ReviewModeration({rows,loadError}:{rows:ModerationReview[];loadError:boolean}){
 const router=useRouter();const [stars,setStars]=useState(0),[reports,setReports]=useState("");const [selected,setSelected]=useState<{row:ModerationReview;action:Action}|null>(null),[reason,setReason]=useState("spam"),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[toast,setToast]=useState<string|null>(null);
 function open(row:ModerationReview,action:Action){setSelected({row,action});setReason("spam");setNote(action==="note"?row.admin_note??"":"");setError("");}
 return <div className="mt-7">{loadError&&<p role="alert" className="mb-5 rounded-2xl bg-peach p-4">Ulasan belum bisa dimuat. Pastikan migration sudah diterapkan.</p>}<div className="mb-5 flex flex-wrap gap-3"><label className="text-sm">Bintang<select value={stars} onChange={e=>setStars(Number(e.target.value))} className={`${input} mt-1`}><option value={0}>Semua bintang</option>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} ★</option>)}</select></label><label className="text-sm">Laporan<select value={reports} onChange={e=>setReports(e.target.value)} className={`${input} mt-1`}><option value="">Semua</option><option value="yes">Ada laporan</option><option value="no">Tanpa laporan</option></select></label></div><DataTable rows={rows.filter(r=>(!stars||r.rating===stars)&&(!reports||(reports==="yes"?r.report_count>0:r.report_count===0)))} rowKey={r=>r.id} searchText={r=>`${r.name} ${r.email} ${r.title} ${r.body}`} filterText={r=>r.status} filters={Object.entries(moderationLabels).filter(([value])=>["pending","approved","hidden"].includes(value)).map(([value,label])=>({value,label}))} columns={[
 {key:"user",label:"Pengguna",render:r=><div className="min-w-40"><p>{r.name}</p><p className="mt-1 break-all text-xs text-muted">{r.email}</p><p className="mt-2 text-purple-800">{r.rating} ★</p><p className="mt-2 text-xs text-muted">Nama publik: {r.display_name}</p><p className="mt-1 text-xs text-muted">{r.order_id?`${r.plan_name} · ${r.order_id.slice(0,8)}`:"Arsip ulasan lama tanpa pesanan"}</p></div>},
 {key:"body",label:"Isi",render:r=><div className="min-w-64 max-w-lg"><p className="font-medium">{r.title}</p><p className="mt-2 max-h-48 overflow-y-auto whitespace-pre-wrap break-words text-sm text-muted">{r.body}</p>{r.admin_note&&<p className="mt-3 rounded-xl bg-peach p-3 text-xs">Catatan admin: {r.admin_note}</p>}</div>},
 {key:"status",label:"Status",render:r=><div><StatusBadge active={r.status==="approved"} label={moderationLabels[r.status]??r.status}/>{r.is_featured&&<p className="mt-2 text-xs text-purple-800">★ Pilihan landing</p>}</div>},
 {key:"reports",label:"Laporan",render:r=><span>{r.open_reports} terbuka / {r.report_count} total</span>},
 {key:"action",label:"Aksi",render:r=><div className="flex min-w-52 flex-wrap gap-2">{r.status!=="hidden"&&<button type="button" className="btn btn-ghost text-xs" onClick={()=>open(r,"hidden")}>Sembunyikan</button>}{r.status!=="approved"&&r.order_id&&<button type="button" className="btn btn-ghost text-xs" onClick={()=>open(r,"restore")}>Setujui</button>}{r.status==="approved"&&<button type="button" className="btn btn-ghost text-xs" onClick={()=>open(r,"feature")}>{r.is_featured?"Lepas Feature":"Feature"}</button>}<button type="button" className="btn btn-ghost text-xs" onClick={()=>open(r,"removed")}>Hapus</button><button type="button" className="btn btn-ghost text-xs" onClick={()=>open(r,"note")}>Catatan</button></div>}
 ]}/><Modal open={Boolean(selected)} title={selected?.action==="note"?"Catatan admin":selected?.action==="feature"?"Pilihan carousel":selected?.action==="restore"?"Setujui ulasan?":selected?.action==="removed"?"Hapus ulasan permanen?":"Sembunyikan ulasan"} onClose={()=>{if(!busy)setSelected(null);}}>{selected&&<form className="grid gap-5" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{const result=await moderateReview(selected.row.id,selected.action,reason,note,!selected.row.is_featured);if(result.error)setError(result.error);else{setSelected(null);setToast("Moderasi tersimpan dan dicatat di audit log.");router.refresh();}}catch{setError("Moderasi belum tersimpan. Coba lagi, ya.");}finally{setBusy(false);}}}><p className="text-sm">{selected.row.plan_name||selected.row.title} · {selected.row.rating} ★</p>{selected.action==="removed"&&<p className="rounded-2xl bg-peach p-4 text-sm">Ulasan akan dihapus permanen. Tindakan ini tidak bisa dibatalkan; alasan dicatat di audit log.</p>}<fieldset disabled={busy} className="grid gap-4">{['hidden','removed'].includes(selected.action)&&<><label className="text-sm">Tindakan<select className={`${input} mt-1`} value={selected.action} onChange={e=>setSelected({...selected,action:e.target.value as Action})}><option value="hidden">Sembunyikan (hidden)</option><option value="removed">Hapus permanen (tidak bisa dibatalkan)</option></select></label><label className="text-sm">Alasan<select className={`${input} mt-1`} value={reason} onChange={e=>setReason(e.target.value)}><option value="spam">Spam</option><option value="sara">SARA</option><option value="lainnya">Lainnya</option></select></label></>}{['hidden','removed','note'].includes(selected.action)?<label className="text-sm">{selected.action==="removed"?"Alasan untuk audit log":"Catatan untuk pemilik ulasan"}<textarea rows={4} maxLength={1000} minLength={selected.action==="note"?0:3} required={selected.action!=="note"||['hidden','removed'].includes(selected.row.status)} value={note} onChange={e=>setNote(e.target.value)} className={`${input} mt-1`}/></label>:<p className="rounded-2xl bg-lilac p-4 text-sm">{selected.action==="restore"?"Ulasan pembelian ini akan disetujui dan tampil publik. Catatan takedown dihapus.":selected.row.is_featured?"Ulasan dilepas dari pilihan landing.":"Ulasan tayang ini akan menjadi pilihan carousel landing."}</p>}{error&&<p role="alert" className="rounded-2xl bg-peach p-4 text-sm">{error}</p>}<div className="flex gap-3"><button type="button" onClick={()=>setSelected(null)} className="btn btn-ghost">Batal</button><button type="submit" className="btn btn-brand">{busy?"Menyimpan…":"Simpan tindakan"}</button></div></fieldset></form>}</Modal>{toast&&<Toast message={toast} onClose={()=>setToast(null)}/>}</div>;
}
